### ISSUE TITLE
kassenbuch.py: dead code kunde.beschreibung?

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/FabLabKasse#32]
```
import FabLabKasse.kassenbuch as k
foo = k.Kunde("hans")
print foo.beschreibung
```

crashes:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "FabLabKasse/kassenbuch.py", line 530, in beschreibung
    if self.rechnung:
AttributeError: Kunde instance has no attribute 'rechnung'
```

is kunde.beschreibung unused?

**Comment by patkan** [comment]
Julian: probably yes.
