### ISSUE TITLE
FAU Card Bezahlung: schönere Fehlerbehandlung

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/FabLabKasse#33]
Wenn man mal zuviel Zeit hat, kann man bei der FAU Card Bezahlung eine schönere Fehlerbehandlung einbauen. Ich habs just4fun auf dem Laptop mal eingeschalten, hab aber natürlich kein Gerät, und bekomm Fehlermeldungen und die Kasse stürtzt ab. Könnte mir vorstellen, dass die Kasse auch abstürtzt, wenn es Fehler mit dem Gerät gibt.

```
Entschuldigung, das Programm wird wegen eines Fehlers beendet. 
 Wenn dir Rückgeld entgangen ist, melde dich bei kasse@fablab.fau.de und gebe folgende Uhrzeit an:2015-07-02 23:12:04.543275.
Traceback (most recent call last):
  File "/home/se/documents/fablab/github/FabLabKasse/FabLabKasse/gui.py", line 548, in payup
    paymentmethod = pm_diag.getSelectedMethodInstance(self, self.shoppingBackend, total)
  File "/home/se/documents/fablab/github/FabLabKasse/FabLabKasse/UI/PaymentMethodDialogCode.py", line 53, in getSelectedMethodInstance
    return self.method(parent, shopping_backend, amount_to_pay)
TypeError: Can't instantiate abstract class FAUCardPayment with abstract methods _show_dialog

Full exception details (stack limit 50):
Traceback (most recent call last):
  File "/home/se/documents/fablab/github/FabLabKasse/FabLabKasse/gui.py", line 548, in payup
    paymentmethod = pm_diag.getSelectedMethodInstance(self, self.shoppingBackend, total)
  File "/home/se/documents/fablab/github/FabLabKasse/FabLabKasse/UI/PaymentMethodDialogCode.py", line 53, in getSelectedMethodInstance
    return self.method(parent, shopping_backend, amount_to_pay)
TypeError: Can't instantiate abstract class FAUCardPayment with abstract methods _show_dialog

Traceback (most recent call last):
  File "/home/se/documents/fablab/github/FabLabKasse/FabLabKasse/gui.py", line 548, in payup
    paymentmethod = pm_diag.getSelectedMethodInstance(self, self.shoppingBackend, total)
  File "/home/se/documents/fablab/github/FabLabKasse/FabLabKasse/UI/PaymentMethodDialogCode.py", line 53, in getSelectedMethodInstance
    return self.method(parent, shopping_backend, amount_to_pay)
TypeError: Can't instantiate abstract class FAUCardPayment with abstract methods _show_dialog
GUI exited
```

**Comment by patkan** [comment]
Der FAUCard-Code liegt doch noch gar nicht im Repo, weil da noch Lizenzfragen zu klären sind?!
Dann tut sich Python natürlich schwer davon eine Instanz zu bilden :-)
Anosnten, wie denkst du könnte man das besser machen?

**Comment by sedrubal** [comment]
Achso dann ist das wohl nicht relevant. Aber sinnvoll wäre solche Warnungen beim Start nach einem Selbsttest anzuzeigen...
