### ISSUE TITLE
AssertionError: paid amount != current total

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/FabLabKasse#46]
187,15 Minuten  x 0,30€ Laserzeit subventioniert (Artikel 9000) = 56,145
Zahlen per Vertrauenskasse (oder Automat)

59€ bezahlen (d.h. Spende)
-> Crash.

Log des ursprünglichen Auftretens:

```
2015-07-09 18:24:19 - root - DEBUG - addOrderLine 9000 None
2015-07-09 18:24:19 - root - DEBUG - updateOrder
2015-07-09 18:24:19 - root - DEBUG - on_order_clicked 0
2015-07-09 18:24:19 - root - DEBUG - updateOrder
2015-07-09 18:24:22 - root - DEBUG - updateOrder
2015-07-09 18:24:23 - root - DEBUG - updateOrder
2015-07-09 18:24:23 - root - DEBUG - updateOrder
2015-07-09 18:24:24 - root - DEBUG - updateOrder
2015-07-09 18:24:26 - root - DEBUG - updateOrder
2015-07-09 18:24:26 - root - DEBUG - updateOrder
2015-07-09 18:24:38 - root - INFO - started payment of 56,15 € with <class 'FabLabKasse.shopping.payment_methods.AutoCashPayment'>
2015-07-09 18:24:39 - root - INFO - canPayout: 26445 with max. rest 5 / to pay: 5615 / allowed overpay: 5000
2015-07-09 18:26:07 - root - INFO - cash accept finished: total 10000
2015-07-09 18:26:16 - root - INFO - trying to pay out 4100 on device 0
2015-07-09 18:27:28 - root - INFO - trying to pay out 100 on device 1
2015-07-09 18:27:33 - root - INFO - cash payout finished: total -4100
2015-07-09 18:27:43 - root - CRITICAL - Entschuldigung, das Programm wird wegen eines Fehlers beendet. 
 Wenn dir Rückgeld entgangen ist, melde dich bei kasse@fablab.fau.de und gebe folgende Uhrzeit an:2015-07-09 18:27:43.642163.
Traceback (most recent call last):
  File "/home/kasse/FabLabKasse/FabLabKasse/gui.py", line 550, in payup
    paymentmethod.execute_and_store()
  File "/home/kasse/FabLabKasse/FabLabKasse/shopping/payment_methods.py", line 145, in execute_and_store
    self.shopping_backend.pay_order(self)
  File "/home/kasse/FabLabKasse/FabLabKasse/shopping/backend/offline_base.py", line 336, in pay_order
    assert method.amount_paid - method.amount_returned == self.get_current_total()
AssertionError
```

**Comment by mgmax** [comment]
This bug is
- [x] #31 
- [x] missing documentation that get_current_total and add_order_line must behave additively, i.e. no "random" or "half-even" rounding of half cents
- [ ] missing assertion that after adding the donation the current total is correct
- [ ] log cart before starting payment

internal details:
- cart total (non-rounded) is 58.145
- shoppingBackend.get_current_total() = Decimal('58.15')
- paid 59€
- [this line](https://github.com/fau-fablab/FabLabKasse/blob/f19b2007933dab9c3b1bbb5d6d3ad9044bec0326/FabLabKasse/shopping/payment_methods.py#L144) adds a donation for the difference between current total [which rounds!] and the paid amount.
  add_order_line( id=9999, amount=2.85)
- shoppingBackend.get_current_total() = Decimal('58.99'), not 60
- crash.

**Comment by mgmax** [comment]
@fau-fablab/kasse I'm gone for the weekend, please help with this
