### ISSUE TITLE
run.py --debug broken

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/FabLabKasse#47]
just prints an error message.

How can I run `python -m FabLabKasse.gui` together with winpdb?

**Comment by patkan** [comment]
`run.py --debug` seems to work for me. However, `python -m FabLabKasse.gui` throws an error indeed.

```
python -m FabLabKasse.gui
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/patrick/Dokumente/FabLab/Kassenterminal/FabLabKasse/FabLabKasse/gui.py", line 60, in <module>
    cfg = scriptHelper.getConfig()
  File "FabLabKasse/scriptHelper.py", line 98, in getConfig
    raise Exception("Cannot open configuration file. If you want to try the program and do not have a config, start ./run.py --example or just copy config.ini.example to config.ini")
Exception: Cannot open configuration file. If you want to try the program and do not have a config, start ./run.py --example or just copy config.ini.example to config.ini
```

**Comment by cod3monk** [comment]
Works, as long as you copy the config.ini file in your cwd.

This is due to getting the config from ./, which is probably not a good idea on the long term. The config file should be loaded from a couple default locations and a location passed via the cli.
